# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'OCTeach' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'Masonry', '~> 1.0.1'
pod 'ReactiveCocoa', '~> 2.5'
pod 'MJExtension', '~> 3.0.12'
pod 'MJRefresh', '~> 3.1.10'
end

target 'OCTeachTests' do

end

target 'OCTeachUITests' do

end

